import assert from "node:assert/strict";
import test from "node:test";
import { WorkManagementDomainError } from "../errors/codes";
import { assertCompletionReadiness, assertDeadlineChangeReason, assertHandoverRecipient, assertNewSubmission, assertNoCycle, assertNoOverlappingHandover, assertPrimaryAssigneeIsNotCollaborator, assertProgress, assertReviewerIndependence, assertSinglePrimaryAssignee, assertTaskAssigneeReference } from "../domain/invariants";
import { task } from "./fixtures";
const code = (fn: () => void, expected: string) => assert.throws(fn, (error: unknown) => error instanceof WorkManagementDomainError && error.code === expected);
test("assignee and reviewer invariants protect distinct responsibilities", () => { code(() => assertSinglePrimaryAssignee([]), "TASK_PRIMARY_ASSIGNEE_CONFLICT"); code(() => assertPrimaryAssigneeIsNotCollaborator([{ userId: "u", role: "COLLABORATOR" }], "u"), "TASK_PARTICIPANT_ROLE_INVALID"); code(() => assertTaskAssigneeReference({ userId: "member", source: "PROJECT_MEMBER" }), "TASK_PARTICIPANT_ROLE_INVALID"); code(() => assertReviewerIndependence(task(), "assignee"), "TASK_REVIEWER_CONFLICT"); });
test("progress, deadline, submission and completion guards fail deterministically", () => { code(() => assertProgress(101), "TASK_PROGRESS_INVALID"); code(() => assertDeadlineChangeReason(true, ""), "TASK_DEADLINE_REASON_REQUIRED"); code(() => assertNewSubmission(1, 1), "TASK_SUBMISSION_IMMUTABLE"); code(() => assertCompletionReadiness({ requiredChecklistComplete: false, requiredOutputsPresent: true, requiredSubtasksComplete: true, blocked: false }), "TASK_REQUIRED_CHECKLIST_INCOMPLETE"); });
test("handover and graph guards reject overlap, self transfer and cycles", () => { code(() => assertHandoverRecipient("u", { id: "u", isActive: true }), "TASK_HANDOVER_SELF_TRANSFER"); code(() => assertNoOverlappingHandover([{ startAt: new Date("2026-07-14"), endAt: null }], { startAt: new Date("2026-07-15"), endAt: null }), "TASK_HANDOVER_CONFLICT"); code(() => assertNoCycle([{ fromId: "a", toId: "b" }, { fromId: "b", toId: "c" }], "c", "a", "TASK_DEPENDENCY_CYCLE"), "TASK_DEPENDENCY_CYCLE"); });
