import assert from "node:assert/strict";
import test from "node:test";
import { createResponsibilityDelegationSnapshot, isResponsibilityDelegationEffectiveAt, requestResponsibilityDelegation, validateResponsibilityDelegationSnapshot, validateResponsibilityDelegationEffects } from "../application/responsibility-delegation";
import { WorkManagementDomainError } from "../errors/codes";

const at = (day = 20): Date => new Date(`2026-08-${String(day).padStart(2, "0")}T00:00:00.000Z`);
const source = () => ({ id: "ra-1", taskId: "task-1", responsibilityCode: "TASK_OWNER", responsibleUserId: "holder", assignedById: "manager", generation: 1, status: "ACTIVE", effectiveAt: at(1), endedAt: null, reason: null, supersedesAssignmentId: null });
const request = (snapshot = createResponsibilityDelegationSnapshot(source()), extra: Readonly<Record<string, unknown>> = {}) => ({ snapshot, id: "dg-1", delegateUserId: "delegate", actorId: "holder", requestedAt: at(20), startsAt: at(21), expiresAt: at(30), reason: "reason", ...extra });
const domain = (error: unknown, code: string): boolean => error instanceof WorkManagementDomainError && error.code === code;
const record = (extra: Readonly<Record<string, unknown>> = {}) => ({ id: "dg-1", taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", delegateUserId: "delegate", requestedById: "holder", generation: 1, status: "REQUESTED", requestedAt: at(20), startsAt: at(21), expiresAt: at(30), acceptedAt: null, endedAt: null, requestReason: null, decisionReason: null, endReason: null, ...extra });
const invalid = (run: () => unknown, code = "TASK_DELEGATION_HISTORY_INVALID") => assert.throws(run, (error: unknown) => domain(error, code));

test("delegation history rejects duplicate IDs and broken generations", () => { invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 2, delegations: [record(), record({ generation: 2 })] })); for (const generation of [0, -1, 1.5]) invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 1, delegations: [record({ generation })] })); });
test("delegation history rejects multiple open delegations", () => { invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 2, delegations: [record(), record({ id: "dg-2", delegateUserId: "other", generation: 2 })] }), "TASK_DELEGATION_ALREADY_OPEN"); });
test("delegation history rejects invalid runtime statuses and dates", () => { for (const value of ["ACTIVE", "", null, 1]) invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 1, delegations: [record({ status: value })] })); for (const value of ["", 1, true, [], {}, new Date("invalid")]) invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 1, delegations: [record({ startsAt: value })] })); });
test("delegation history rejects broken source-assignment anchors", () => { for (const patch of [{ taskId: "foreign" }, { sourceAssignmentId: "other" }, { responsibilityCode: "TASK_CONTRIBUTOR" }, { delegatorUserId: "other" }]) invalid(() => validateResponsibilityDelegationSnapshot({ taskId: "task-1", sourceAssignmentId: "ra-1", responsibilityCode: "TASK_OWNER", delegatorUserId: "holder", version: 1, delegations: [record(patch)] })); });
test("delegation lifecycle rejects malformed command objects", () => { for (const value of [null, undefined, 1, true, "bad", [], {}]) assert.throws(() => requestResponsibilityDelegation(value), (error: unknown) => domain(error, "TASK_DELEGATION_INVALID")); });
test("empty whitespace and non-string delegation reasons fail closed", () => { for (const value of ["", " ", 1, true, [], {}, () => undefined]) assert.throws(() => requestResponsibilityDelegation(request(undefined, { reason: value })), (error: unknown) => domain(error, "TASK_DELEGATION_INVALID")); });
test("delegation effectiveness is derived from accepted status and time window", () => { const accepted = record({ status: "ACCEPTED", acceptedAt: at(20) }); assert.equal(isResponsibilityDelegationEffectiveAt(accepted, at(20)), false); assert.equal(isResponsibilityDelegationEffectiveAt(accepted, at(21)), true); assert.equal(isResponsibilityDelegationEffectiveAt(accepted, at(29)), true); assert.equal(isResponsibilityDelegationEffectiveAt(accepted, at(30)), false); assert.equal(isResponsibilityDelegationEffectiveAt(record(), at(22)), false); for (const state of ["REJECTED", "REVOKED", "EXPIRED"]) { const closed = state === "EXPIRED" ? record({ status: state, endedAt: at(30) }) : record({ status: state, endedAt: at(22) }); assert.equal(isResponsibilityDelegationEffectiveAt(closed, at(22)), false); } });
test("delegation effects expose exact type-specific trusted metadata", () => { const result = requestResponsibilityDelegation(request()); const effect = result.effects[0]; assert.equal(effect?.type, "RESPONSIBILITY_DELEGATION_REQUESTED"); assert.equal(effect?.delegationId, "dg-1"); assert.equal(effect?.sourceAssignmentId, "ra-1"); assert.equal(effect?.delegatorUserId, "holder"); assert.equal(effect?.delegateUserId, "delegate"); assert.equal(effect?.requestReason, "reason"); invalid(() => validateResponsibilityDelegationEffects([{ type: "BAD" }]), "TASK_DELEGATION_INVALID"); });
test("delegation operation outputs are isolated from mutable source records and dates", () => { const mutableSource = source(); const mutableDate = at(20); const raw = request(createResponsibilityDelegationSnapshot(mutableSource), { requestedAt: mutableDate }); const result = requestResponsibilityDelegation(raw); mutableSource.responsibleUserId = "changed"; mutableDate.setFullYear(2030); assert.equal(result.snapshot.delegatorUserId, "holder"); assert.deepEqual(result.snapshot.delegations[0]?.requestedAt, at(20)); });
test("later delegation operations do not mutate prior snapshots", () => { const first = requestResponsibilityDelegation(request()); const before = structuredClone(first.snapshot); requestResponsibilityDelegation(request(createResponsibilityDelegationSnapshot(source()), { id: "other" })); assert.deepEqual(first.snapshot, before); });
test("delegation effects are isolated from caller mutation", () => { const result = requestResponsibilityDelegation(request()); const effect = result.effects[0]; assert.notEqual(effect, undefined); if (effect === undefined) return; effect.occurredAt.setFullYear(2030); assert.deepEqual(result.snapshot.delegations[0]?.requestedAt, at(20)); });
test("delegation lifecycle preserves command snapshot date and source-assignment inputs", () => { const assignment = source(); const snap = createResponsibilityDelegationSnapshot(assignment); const raw = request(snap); const before = structuredClone(raw); requestResponsibilityDelegation(raw); assert.deepEqual(raw, before); assert.deepEqual(assignment, source()); });
test("delegation never changes the operational assignee", () => { const result = requestResponsibilityDelegation(request()); assert.equal("primaryAssigneeId" in result.snapshot, false); });
test("delegation never changes the responsibility assignment holder", () => { const result = requestResponsibilityDelegation(request()); assert.equal(result.snapshot.delegatorUserId, "holder"); });
test("ProjectMember participant reviewer approver and notification recipients are not implicit delegates", () => { const result = requestResponsibilityDelegation(request()); assert.deepEqual(result.snapshot.delegations.map((item) => item.delegateUserId), ["delegate"]); });
