export const WORK_MANAGEMENT_ACTIVITY_TYPES = [
  "TASK_CREATED", "TASK_ASSIGNED", "TASK_ACCEPTED", "TASK_CLARIFICATION_REQUESTED", "TASK_STARTED", "TASK_PROGRESS_UPDATED", "TASK_EXTENSION_REQUESTED", "TASK_DEADLINE_CHANGED", "TASK_PAUSED", "TASK_RESUMED", "TASK_BLOCKED", "TASK_UNBLOCKED", "TASK_SUBMITTED", "TASK_CHANGES_REQUESTED", "TASK_RESULT_APPROVED", "TASK_COMPLETED", "TASK_REOPENED", "TASK_CANCELLED", "TASK_ARCHIVED", "TASK_RESTORED", "TASK_HANDOVER_REQUESTED", "TASK_HANDOVER_ACCEPTED", "TASK_HANDOVER_REJECTED", "TASK_HANDOVER_APPROVED", "TASK_HANDOVER_EXECUTED",
] as const;

export type WorkManagementActivityType =
  (typeof WORK_MANAGEMENT_ACTIVITY_TYPES)[number];
