export const WORK_MANAGEMENT_AUDIT_ACTIONS = [
  "TASK_CREATE", "TASK_ASSIGN", "TASK_ACCEPT", "TASK_REQUEST_CLARIFICATION", "TASK_START", "TASK_UPDATE_PROGRESS", "TASK_REQUEST_EXTENSION", "TASK_CHANGE_DEADLINE", "TASK_PAUSE", "TASK_RESUME", "TASK_BLOCK", "TASK_UNBLOCK", "TASK_SUBMIT", "TASK_REQUEST_CHANGES", "TASK_APPROVE_RESULT", "TASK_CONFIRM_COMPLETION", "TASK_REOPEN", "TASK_CANCEL", "TASK_ARCHIVE", "TASK_RESTORE", "TASK_REQUEST_HANDOVER", "TASK_ACCEPT_HANDOVER", "TASK_REJECT_HANDOVER", "TASK_APPROVE_HANDOVER", "TASK_EXECUTE_HANDOVER",
] as const;

export type WorkManagementAuditAction =
  (typeof WORK_MANAGEMENT_AUDIT_ACTIONS)[number];
