import { PrismaClient } from "@prisma/client";

// Workaround for running script outside Next.js environment
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = `${process.env.DATABASE_URL}`;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function runQa() {
  console.log("=== STARTING MATERIALS MVP QA TEST ===");
  
  const testMaterialCode = `TEST-MAT-${Date.now()}`;
  let projectId: string | null = null;
  let materialItemId: string | null = null;
  
  try {
    // 1. Get an active project
    const project = await prisma.project.findFirst({
      where: { status: "ACTIVE" }
    });
    
    if (!project) {
      throw new Error("No active project found to run the test.");
    }
    projectId = project.id;
    console.log(`[1] Selected Project: ${project.name} (${project.id})`);

    // 2. Create Material Item
    const material = await prisma.materialItem.create({
      data: {
        code: testMaterialCode,
        name: "Vật tư Test QA",
        unit: "kg",
        group: "Test",
        description: "Generated by QA script"
      }
    });
    materialItemId = material.id;
    console.log(`[2] Created test material: ${material.name} (${material.code})`);

    // 3. Import 100 units
    console.log(`[3] Simulating IMPORT of 100 units...`);
    await prisma.$transaction(async (tx) => {
      await tx.projectMaterialStock.upsert({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
        update: { stock: { increment: 100 } },
        create: { projectId: project.id, materialItemId: material.id, stock: 100, minStockLevel: 10 }
      });
      await tx.materialMovement.create({
        data: {
          projectId: project.id,
          materialItemId: material.id,
          type: "IMPORT",
          quantity: 100,
          movementDate: new Date(),
          notes: "QA Import 100"
        }
      });
    });

    let stockCheck = await prisma.projectMaterialStock.findUnique({
      where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
    });
    console.log(`[3] Current Stock after IMPORT: ${stockCheck?.stock}`);
    if (Number(stockCheck?.stock) !== 100) throw new Error("Stock should be 100!");

    // 4. Export 30 units
    console.log(`[4] Simulating EXPORT of 30 units...`);
    await prisma.$transaction(async (tx) => {
      const stock = await tx.projectMaterialStock.findUnique({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
      });
      
      if (!stock || Number(stock.stock) < 30) {
        throw new Error("Not enough stock for export!");
      }
      
      await tx.projectMaterialStock.update({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
        data: { stock: { decrement: 30 } }
      });
      
      await tx.materialMovement.create({
        data: {
          projectId: project.id,
          materialItemId: material.id,
          type: "EXPORT",
          quantity: 30,
          movementDate: new Date(),
          notes: "QA Export 30"
        }
      });
    });

    stockCheck = await prisma.projectMaterialStock.findUnique({
      where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
    });
    console.log(`[4] Current Stock after EXPORT: ${stockCheck?.stock}`);
    if (Number(stockCheck?.stock) !== 70) throw new Error("Stock should be 70!");

    // 5. Try to export 999999 units (should fail)
    console.log(`[5] Simulating over-export of 999999 units...`);
    let overExportFailed = false;
    try {
      await prisma.$transaction(async (tx) => {
        const stock = await tx.projectMaterialStock.findUnique({
          where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
        });
        
        if (!stock || Number(stock.stock) < 999999) {
          throw new Error("Số lượng xuất vượt quá tồn kho hiện tại");
        }
        
        await tx.projectMaterialStock.update({
          where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
          data: { stock: { decrement: 999999 } }
        });
      });
    } catch (e: any) {
      if (e.message === "Số lượng xuất vượt quá tồn kho hiện tại") {
        overExportFailed = true;
        console.log("[5] Success: Over-export correctly blocked by transaction logic.");
      } else {
        throw e;
      }
    }
    
    if (!overExportFailed) {
      throw new Error("Over-export was NOT blocked!");
    }

  } catch (err: any) {
    console.error("QA TEST FAILED:", err);
  } finally {
    // 6. Cleanup
    console.log(`[6] Cleaning up test data...`);
    if (materialItemId && projectId) {
      await prisma.materialMovement.deleteMany({
        where: { materialItemId, projectId }
      });
      await prisma.projectMaterialStock.delete({
        where: { projectId_materialItemId: { projectId, materialItemId } }
      });
      await prisma.materialItem.delete({
        where: { id: materialItemId }
      });
      console.log(`[6] Cleanup completed.`);
    }
    
    await prisma.$disconnect();
    console.log("=== QA TEST FINISHED ===");
  }
}

runQa().catch(console.error);
