import { PrismaClient } from "@prisma/client";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { applyMaterialMovement } from "../src/lib/materials/ledger";

const connectionString = `${process.env.DATABASE_URL}`;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

async function readStock(projectId: string, materialItemId: string) {
  return prisma.projectMaterialStock.findUnique({
    where: { projectId_materialItemId: { projectId, materialItemId } },
  });
}

async function runQa() {
  console.log("=== STARTING MATERIALS FULL FLOW QA TEST ===");

  const testRunId = `QA-MATERIALS-${Date.now()}`;
  const testMaterialCode = `${testRunId}-MAT`;
  let projectId: string | null = null;
  let materialItemId: string | null = null;

  try {
    const project = await prisma.project.findFirst({
      where: { status: "ACTIVE", deletedAt: null },
      select: { id: true, name: true, code: true },
      orderBy: { createdAt: "desc" },
    });

    assert(project, "No active project found to run the materials QA flow.");
    projectId = project.id;
    console.log(`[1] Selected project: ${project.name} (${project.code})`);

    const material = await prisma.materialItem.create({
      data: {
        projectId: project.id,
        code: testMaterialCode,
        name: "Vật tư QA tự động",
        unit: "kg",
        group: "QA",
        description: `Generated by ${testRunId}`,
      },
      select: { id: true, code: true, name: true },
    });
    materialItemId = material.id;
    console.log(`[2] Created test material: ${material.name} (${material.code})`);

    await prisma.$transaction((tx) =>
      applyMaterialMovement(tx, {
        projectId: project.id,
        materialItemId: material.id,
        type: "IMPORT",
        quantity: 100,
        movementDate: new Date(),
        notes: `${testRunId}: import 100`,
        minStockLevel: 10,
      })
    );

    let stock = await readStock(project.id, material.id);
    assert(Number(stock?.stock) === 100, `Expected stock 100 after import, got ${stock?.stock}`);
    console.log("[3] Import 100 passed. Stock = 100");

    await prisma.$transaction((tx) =>
      applyMaterialMovement(tx, {
        projectId: project.id,
        materialItemId: material.id,
        type: "EXPORT",
        quantity: 30,
        movementDate: new Date(),
        notes: `${testRunId}: export 30`,
      })
    );

    stock = await readStock(project.id, material.id);
    assert(Number(stock?.stock) === 70, `Expected stock 70 after export, got ${stock?.stock}`);
    console.log("[4] Export 30 passed. Stock = 70");

    let blockedOverExport = false;
    try {
      await prisma.$transaction((tx) =>
        applyMaterialMovement(tx, {
          projectId: project.id,
          materialItemId: material.id,
          type: "EXPORT",
          quantity: 999999,
          movementDate: new Date(),
          notes: `${testRunId}: blocked over-export`,
        })
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      blockedOverExport = message.includes("vượt quá tồn kho");
      if (!blockedOverExport) throw error;
    }
    assert(blockedOverExport, "Over-export was not blocked.");
    console.log("[5] Over-export was blocked.");

    stock = await readStock(project.id, material.id);
    assert(Number(stock?.stock) === 70, `Expected stock to remain 70, got ${stock?.stock}`);

    const movements = await prisma.materialMovement.findMany({
      where: { projectId: project.id, materialItemId: material.id },
      orderBy: { createdAt: "asc" },
      select: { type: true, quantity: true, notes: true },
    });
    assert(movements.length === 2, `Expected 2 movements, got ${movements.length}`);
    assert(movements[0].type === "IMPORT" && Number(movements[0].quantity) === 100, "Import movement was not recorded correctly.");
    assert(movements[1].type === "EXPORT" && Number(movements[1].quantity) === 30, "Export movement was not recorded correctly.");
    console.log("[6] Movement history passed.");

    console.log("=== MATERIALS QA TEST PASSED ===");
  } finally {
    console.log("[7] Cleaning up QA data.");
    if (materialItemId && projectId) {
      await prisma.materialMovement.deleteMany({ where: { materialItemId, projectId } });
      await prisma.projectMaterialStock.deleteMany({ where: { materialItemId, projectId } });
      await prisma.materialItem.deleteMany({
        where: {
          id: materialItemId,
          code: testMaterialCode,
          description: { contains: testRunId },
        },
      });

      const remaining = await prisma.materialItem.count({ where: { code: testMaterialCode } });
      assert(remaining === 0, `Cleanup failed. Remaining test materials: ${remaining}`);
      console.log("[7] Cleanup completed.");
    }

    await prisma.$disconnect();
    await pool.end();
  }
}

runQa().catch((error) => {
  console.error("QA TEST FAILED:", error);
  process.exitCode = 1;
});

/*
import { PrismaClient } from "@prisma/client";

// Workaround for running script outside Next.js environment
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = `${process.env.DATABASE_URL}`;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function runQa() {
  console.log("=== STARTING MATERIALS MVP QA TEST ===");
  
  const testMaterialCode = `TEST-MAT-${Date.now()}`;
  let projectId: string | null = null;
  let materialItemId: string | null = null;
  
  try {
    // 1. Get an active project
    const project = await prisma.project.findFirst({
      where: { status: "ACTIVE" }
    });
    
    if (!project) {
      throw new Error("No active project found to run the test.");
    }
    projectId = project.id;
    console.log(`[1] Selected Project: ${project.name} (${project.id})`);

    // 2. Create Material Item
    const material = await prisma.materialItem.create({
      data: {
        code: testMaterialCode,
        name: "Vật tư Test QA",
        unit: "kg",
        group: "Test",
        description: "Generated by QA script"
      }
    });
    materialItemId = material.id;
    console.log(`[2] Created test material: ${material.name} (${material.code})`);

    // 3. Import 100 units
    console.log(`[3] Simulating IMPORT of 100 units...`);
    await prisma.$transaction(async (tx) => {
      await tx.projectMaterialStock.upsert({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
        update: { stock: { increment: 100 } },
        create: { projectId: project.id, materialItemId: material.id, stock: 100, minStockLevel: 10 }
      });
      await tx.materialMovement.create({
        data: {
          projectId: project.id,
          materialItemId: material.id,
          type: "IMPORT",
          quantity: 100,
          movementDate: new Date(),
          notes: "QA Import 100"
        }
      });
    });

    let stockCheck = await prisma.projectMaterialStock.findUnique({
      where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
    });
    console.log(`[3] Current Stock after IMPORT: ${stockCheck?.stock}`);
    if (Number(stockCheck?.stock) !== 100) throw new Error("Stock should be 100!");

    // 4. Export 30 units
    console.log(`[4] Simulating EXPORT of 30 units...`);
    await prisma.$transaction(async (tx) => {
      const stock = await tx.projectMaterialStock.findUnique({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
      });
      
      if (!stock || Number(stock.stock) < 30) {
        throw new Error("Not enough stock for export!");
      }
      
      await tx.projectMaterialStock.update({
        where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
        data: { stock: { decrement: 30 } }
      });
      
      await tx.materialMovement.create({
        data: {
          projectId: project.id,
          materialItemId: material.id,
          type: "EXPORT",
          quantity: 30,
          movementDate: new Date(),
          notes: "QA Export 30"
        }
      });
    });

    stockCheck = await prisma.projectMaterialStock.findUnique({
      where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
    });
    console.log(`[4] Current Stock after EXPORT: ${stockCheck?.stock}`);
    if (Number(stockCheck?.stock) !== 70) throw new Error("Stock should be 70!");

    // 5. Try to export 999999 units (should fail)
    console.log(`[5] Simulating over-export of 999999 units...`);
    let overExportFailed = false;
    try {
      await prisma.$transaction(async (tx) => {
        const stock = await tx.projectMaterialStock.findUnique({
          where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } }
        });
        
        if (!stock || Number(stock.stock) < 999999) {
          throw new Error("Số lượng xuất vượt quá tồn kho hiện tại");
        }
        
        await tx.projectMaterialStock.update({
          where: { projectId_materialItemId: { projectId: project.id, materialItemId: material.id } },
          data: { stock: { decrement: 999999 } }
        });
      });
    } catch (e: any) {
      if (e.message === "Số lượng xuất vượt quá tồn kho hiện tại") {
        overExportFailed = true;
        console.log("[5] Success: Over-export correctly blocked by transaction logic.");
      } else {
        throw e;
      }
    }
    
    if (!overExportFailed) {
      throw new Error("Over-export was NOT blocked!");
    }

  } catch (err: any) {
    console.error("QA TEST FAILED:", err);
  } finally {
    // 6. Cleanup
    console.log(`[6] Cleaning up test data...`);
    if (materialItemId && projectId) {
      await prisma.materialMovement.deleteMany({
        where: { materialItemId, projectId }
      });
      await prisma.projectMaterialStock.delete({
        where: { projectId_materialItemId: { projectId, materialItemId } }
      });
      await prisma.materialItem.delete({
        where: { id: materialItemId }
      });
      console.log(`[6] Cleanup completed.`);
    }
    
    await prisma.$disconnect();
    console.log("=== QA TEST FINISHED ===");
  }
}

runQa().catch(console.error);
*/
