import { z } from "zod";
import { CONFIDENTIALITY_LEVELS, TASK_PRIORITIES } from "../domain/types";

const id = z.string().min(1); const text = z.string().trim().min(1); const optionalText = z.string().trim().max(10_000).optional(); const date = z.coerce.date();
const versionedTaskCommandBase = z.object({ taskId: id, expectedVersion: z.number().int().nonnegative() });
export const createTaskSchema = z.object({ title: z.string().trim().min(3).max(300), description: optionalText, primaryAssigneeId: id.optional(), projectId: id.optional(), plannedStartAt: date.optional(), currentDueAt: date.optional(), priority: z.enum(TASK_PRIORITIES).default("NORMAL"), confidentiality: z.enum(CONFIDENTIALITY_LEVELS).default("NORMAL") }).strict().refine((value) => !value.plannedStartAt || !value.currentDueAt || value.currentDueAt >= value.plannedStartAt, { message: "TASK_DATE_RANGE_INVALID", path: ["currentDueAt"] });
export const assignTaskSchema = z.object({ taskId: id, primaryAssigneeId: id, reason: optionalText, expectedVersion: z.number().int().nonnegative() }).strict();
export const acceptTaskSchema = z.object({ taskId: id, expectedVersion: z.number().int().nonnegative() }).strict();
export const startTaskSchema = versionedTaskCommandBase.strict();
export const clarificationSchema = z.object({ taskId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const progressUpdateSchema = z.object({ taskId: id, progressPercent: z.number().min(0).max(100), completedWork: optionalText, remainingWork: optionalText, blocker: optionalText, risk: optionalText, supportRequest: optionalText, timeSpent: z.number().min(0).optional(), expectedVersion: z.number().int().nonnegative() }).strict();
export const extensionRequestSchema = z.object({ taskId: id, requestedDueAt: date, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const changeDeadlineSchema = z.object({ taskId: id, currentDueAt: date, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const submissionSchema = z.object({ taskId: id, summary: text.max(10_000), remainingIssue: optionalText, expectedVersion: z.number().int().nonnegative() }).strict();
export const reviewSchema = z.object({ taskId: id, submissionId: id, comment: optionalText, expectedVersion: z.number().int().nonnegative() }).strict();
export const approveSubmissionSchema = reviewSchema;
export const changesRequestSchema = z.object({ taskId: id, submissionId: id, reason: text.max(5_000), dueAt: date.optional(), expectedVersion: z.number().int().nonnegative() }).strict();
export const completeTaskSchema = z.object({ taskId: id, expectedVersion: z.number().int().nonnegative() }).strict();
export const reopenTaskSchema = z.object({ taskId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const pauseTaskSchema = z.object({ taskId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const resumeTaskSchema = versionedTaskCommandBase.extend({ reason: optionalText }).strict();
export const blockTaskSchema = versionedTaskCommandBase.extend({ reason: text.max(5_000) }).strict();
export const unblockTaskSchema = versionedTaskCommandBase.extend({ resolution: text.max(5_000) }).strict();
export const cancelTaskSchema = z.object({ taskId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const archiveTaskSchema = z.object({ taskId: id, expectedVersion: z.number().int().nonnegative() }).strict();
export const restoreTaskSchema = versionedTaskCommandBase.extend({ reason: optionalText }).strict();
export const subtaskSchema = createTaskSchema.extend({ parentTaskId: id }).strict();
export const dependencySchema = z.object({ predecessorTaskId: id, successorTaskId: id, expectedVersion: z.number().int().nonnegative() }).strict().refine((value) => value.predecessorTaskId !== value.successorTaskId, { message: "TASK_DEPENDENCY_CYCLE" });
export const handoverRequestSchema = z.object({ taskId: id, receiverId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const acceptHandoverSchema = z.object({ taskId: id, handoverId: id, expectedVersion: z.number().int().nonnegative() }).strict();
export const rejectHandoverSchema = z.object({ taskId: id, handoverId: id, reason: text.max(5_000), expectedVersion: z.number().int().nonnegative() }).strict();
export const approveHandoverSchema = acceptHandoverSchema;
export const handoverDecisionSchema = acceptHandoverSchema;
export const executeHandoverSchema = versionedTaskCommandBase.extend({ handoverId: id }).strict();
export const delegationSchema = z.object({ delegateId: id, startsAt: date, endsAt: date.optional(), reason: text.max(5_000) }).strict().refine((value) => !value.endsAt || value.endsAt >= value.startsAt, { message: "TASK_DATE_RANGE_INVALID" });
export const revokeDelegationSchema = z.object({ delegationId: id, reason: text.max(5_000) }).strict();
export const responsibilityAssignmentSchema = z.object({ userId: id, title: text.max(300), scopeType: z.enum(["COMPANY", "DEPARTMENT", "PROJECT", "SPECIFIC"]), projectId: id.optional(), startsAt: date, endsAt: date.optional(), reason: text.max(5_000) }).strict().refine((value) => !value.endsAt || value.endsAt >= value.startsAt, { message: "TASK_DATE_RANGE_INVALID" });
